#version=3.9

services:
  reverse-proxy:
    image: nginx:latest
    container_name: flask-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  cache:
    image: redis:latest
    container_name: flask-cache
    ports:
      - "6379:6379"
    volumes:
      - ./cache:/cache-data
  backend:
    build: ./server
    volumes:
      - ./server/app/:/code/
    ports:
      - "3000:3000"
    container_name: flask-server
    env_file:
      - ./server/.flaskenv
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: pg-db
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env