name: Test Flask Server
on: push

jobs:
  runner-job:
    # Containers must use linux base github runners
    runs-on: ubuntu-latest
  
    # Service containers to run with runner-job
    services:
      pg-db:
        image: postgres:15.0-alpine
        env:
           POSTGRES_USER: ${{secrets.POSTGRES_USER}}
           POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
           POSTGRES_DB: ${{secrets.POSTGRES_DB}}
           POSTGRES_HOST: localhost
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      test-db:
        image: postgres:15.0-alpine
        env:
           POSTGRES_USER: ${{secrets.POSTGRES_USER}}
           POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
           POSTGRES_DB: ${{secrets.TEST_DB}}
           POSTGRES_HOST: localhost
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5423:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      

      - name: Install python dependencies
        run: |
          cd server
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Change to app flask app directory and test with coverage and pytest
        env:
          TEST_URI: ${{secrets.TEST_URI}}
          DATABASE_URI: ${{secrets.DATABASE_URI}}
        run: |
          cd server/app
          coverage run -m pytest 
       
        

